# Generated by Django 5.0.6 on 2024-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_items1_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items1',
            name='item_image',
            field=models.CharField(default='https://t3.ftcdn.net/jpg/07/10/34/00/240_F_710340033_NThiSbQxwd2tK9mzDDFB68OTkfKPhdC5.jpg', max_length=5000),
        ),
    ]
